### ISSUE TITLE
Improve/extend Grafana dashboards for Testnet

### ISSUE THREAD

**Issue by mlegner** [MystenLabs/walrus#1056]
- [ ] Show SUI balances based on wallet addresses reported since #1025.
- [x] Show shard distribution (depends or #1088).
- [x] Number of registered and certified blobs.
- [ ] Aggregators and publishers.
- [x] Shard migration (depends on #1087).
- [ ] Public dashboard.
