### ISSUE TITLE
Major Epic: Invalid Blob ID handling

### ISSUE THREAD

**Issue by gdanezis** [MystenLabs/walrus#257]
- [x] Extract a proof of invalid blob ID. (#304)
- [x] Share the proof of invalid blob ID with other storage nodes. (#331, #332)
- [x] Node returns a signed statement about an invalid blob ID. (#331, #332)
- [x] Node returns a statement that a blob is invalid to readers with reference to the event (#418 , #449)
- [x] Node deletes metadata and slivers from invalid blobs from the DB (#432 )
- [x] Certificates of invalid blob ID can be uploaded on chain. (#90)
- [x] Nodes record events about invalid blob IDs. (#314)
- [x] ~~Nodes can respond to challenges using the events about invalid blob IDs. (Now tracked as part of #256)~~
