### ISSUE TITLE
Major Epic: Handle deny list logic

### ISSUE THREAD

**Issue by gdanezis** [MystenLabs/walrus#258]
- [ ] Allow storage nodes to add blob ID to a deny list.
- [ ] Allow others to read the deny list to not ask for blob ID or not challenge
- [ ] When >2/3 storage nodes deny, allow others to auto-deny and drop blob ID.
