### ISSUE TITLE
Major Epic: Implement Shard recovery

### ISSUE THREAD

**Issue by gdanezis** [MystenLabs/walrus#259]
In same epoch (write path) (Devnet): 
- [x] when a blob ID is certified download missing slivers to node from others. (#279)

Across epochs (Testnet): 
- [x] Get a full list of live certified blob IDs from past events.
- [x] Download all missing metadata (if necessary) and slivers. 
- [x] Make available sync done signed message.
- [x] Post sync done message on chain.
