### ISSUE TITLE
Provide more customization in Rust SDK for contract interactions

### ISSUE THREAD

**Issue by karlwuest** [MystenLabs/walrus#262]
- [ ] Allow specifying which payment coins to use
- [x] Merge payment coins before buying a storage resource in a PTB if necessary (#1211)
- [ ] Clean up coins with zero balance
- [x] Provide functionality to get all owned storage resources / blob objects -> #739 
- [x] Make sui bindings more ptb friendly & allow multiple operations in one transaction (#1135 , #1211)
