### ISSUE TITLE
Epic: Implement mechanisms to extend blob lifetimes

### ISSUE THREAD

**Issue by mlegner** [MystenLabs/walrus#583]
This requires changes at different levels:

- [X] Smart contracts + events (#690)
- [X] Status update for blob in storage nodes
- [X] Sui bindings -> see [WAL-371](https://linear.app/mysten-labs/issue/WAL-371/add-sui-bindings-for-blob-extensions)
- [X] Client code to initiate blob extension -> see [WAL-372](https://linear.app/mysten-labs/issue/WAL-372/integrate-blob-extensions-into-the-cli)
