### ISSUE TITLE
Redeploy the Walrus Devnet (and possibly the Walrus Sites contracts)

### ISSUE THREAD

**Issue by mlegner** [MystenLabs/walrus#652]
## Tasks

- [x] Post an announcement as a [discussion in the walrus-docs repository](https://github.com/MystenLabs/walrus-docs/discussions/new?category=announcements). Draft below. -> https://github.com/MystenLabs/walrus-docs/discussions/103
- [x] Merge https://github.com/MystenLabs/sui-operations/pull/4058.
- [x] Bump the `devnet` branch in this repository to the latest `main`.
- [x] Merge https://github.com/MystenLabs/walrus-docs/pull/102 and all PRs it depends on.
- [x] Comment at https://github.com/MystenLabs/walrus-docs/discussions/103 before starting any redeployment.
- [x] Stop any running load generator
- [x] Run the [deploy workflow](https://github.com/MystenLabs/sui-operations/actions/workflows/walrus-deploy.yaml) with the latest `devnet` commit, checking the "Clear /opt/walrus/db directories during deploy + redeploy system contract" option and using 1000 shards.
- [x] Merge https://github.com/MystenLabs/walrus-sites/pull/155.
- [x] Re-deploy all existing Walrus Sites (see https://github.com/MystenLabs/walrus-docs/issues/93 for a list) and verify that they are accessible. If we don't upgrade Walrus Sites, this can be done with `site-builder update --force` otherwise a new `site-builder publish` is necessary.
- [x] Update the docs with the new contract and object addresses
- [x] Restart load generator with updated system object
- [x] Comment at https://github.com/MystenLabs/walrus-docs/discussions/103 when everything is finished and up again.

If we also want to update the Walrus Sites contracts, we need to do the following:

- [ ] Deploy the latest walrus-sites contracts.
- [ ] Update the package in the [site-builder config](https://github.com/MystenLabs/walrus-sites/blob/main/site-builder/assets/builder-example.yaml).
- [ ] Update the Sites Portal.
- [ ] Update the SuiNS pointers for all pages.
- [ ] Update the `*_OBJECT` [variables](https://github.com/MystenLabs/walrus-docs/settings/variables/actions).

## Announcement draft

Dear builders,

Thank you very much for trying out Walrus and providing feedback at this early stage. Based on your
valuable input, we have made several improvements to the Walrus system.

We will update our Devnet on Monday, 2024-08-12, deploying new contracts and binaries and wiping all
data currently stored on Walrus. This means that you will have to download the new binary and
configuration and re-upload any previously stored data.

This also affects all deployed Walrus Sites, which you will have to re-deploy. Further details and 
information about changes will be provided in our docs, the draft is already available
[here](https://mystenlabs.github.io/walrus-docs/pr-preview/pr-102/blog/02_devnet_update.html).

During the redeployment, Walrus and Walrus Sites will be unavailable, including our own sites like
<https://docs.walrus.site/>.

We will comment below this announcement when we start with the upgrade process and again when the
re-deployed system is up.

Thank you very much for your patience and please continue to provide feedback and feature requests.

With best wishes,
The Walrus team

cc @MystenLabs/walrus
