### ISSUE TITLE
Revise all API (node, aggregator, publisher)

### ISSUE THREAD

**Issue by mlegner** [MystenLabs/walrus#997]
Includes the following (not necessarily exhaustive):

- [X] ~~Change the recovery-symbol path to something like ~~`~~/v1/recovery/:blob_id/:sliver_type/:sliver_pair_index/:target_pair_index~~`~~ (see #542, #952)~~
- [ ] Decide which node APIs are "internal" and add documentation that authentication may be required for them in the future
- [ ] Potentially combine some API endpoints to reduce overhead
- [X] Make response formats (especially errors) on aggregator/publisher consistent with those on the storage nodes
